style:
  - changed-files:
    - any-glob-to-any-file: 'contents/scss/**'

CI:
  - all:
    - changed-files:
      - any-glob-to-any-file: '.github/**'
      - all-globs-to-all-files: '!.github/ISSUE_TEMPLATE/**'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - '**/*.markdown'

docker:
  - changed-files:
    - any-glob-to-any-file: 'docker/**'

pages:
  - changed-files:
    - any-glob-to-any-file: 'contents/pages/**'

'roki.log/post update':
  - changed-files:
    - any-glob-to-any-file: 'contents/roki.log/**'

'roki.diary/post update':
  - changed-files:
    - any-glob-to-any-file: 'contents/roki.diary/**'
