# BuildKit configuration for ARM64 builds
[worker.oci]
  gc = true
  gckeepstorage = 20000

[[worker.oci.gcpolicy]]
  keepBytes = 20000000000
  keepDuration = 86400
  filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]

[[worker.oci.gcpolicy]]
  all = true
  keepBytes = 50000000000