enabled: true
restylers:
  - name: stylish-haskell
    include:
      - "**/*.hs"
  - name: dhall-format
    include:
      - "**/*.dhall"
pull_requests: true
statuses:
  differences: true
  error: true
labels:
  - refactoring
ignore_labels:
  - restyled-ignore

