name:       roki-web
version:    2.0.0.0
category:   Web
author:     Roki
maintainer: falgon53@yahoo.co.jp
copyright:  Copyright (c) 2020- Roki
license:    BSD3
github:     roki/roki-web

extra-source-files:
    - README.md

dependencies:
    - base
    - binary
    - hakyll
    - tagsoup
    - process
    - bytestring
    - unordered-containers
    - basic-prelude
    - pandoc
    - filepath
    - time
    - text
    - mtl
    - containers
    - hjsmin
    - extra
    - optparse-applicative
    - gitrev
    - file-embed
    - transformers

library:
    source-dirs:
        - src

executables:
    site:
        source-dirs: app
        main:        site/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        dependencies:
        - roki-web
        - aeson
        - morpheus-graphql-client
        - network-uri
        - req
        - utf8-string
        - dhall
        - lucid
    spa:
        source-dirs: app
        main:        spa/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        dependencies:
        - roki-web
