name:       roki-web
version:    2.0.0.0
category:   Web
author:     Roki
maintainer: falgon53@yahoo.co.jp
copyright:  Copyright (c) 2020- Roki
license:    BSD3
github:     roki/roki-web

extra-source-files:
    - README.md

dependencies:
    - base

library:
    source-dirs:
        - src
    dependencies:
      - aeson
      - binary
      - gitrev
      - file-embed
      - bytestring
      - text
      - transformers
      - extra
      - filepath
      - lucid
      - process
      - ansi-terminal-types
      - hakyll
      - rio
      - hjsmin
      - safe-exceptions
      - morpheus-graphql-client
      - network-uri
      - utf8-string
      - hpack
      - pandoc-types
      - yaml
      - stack
      - network-uri
      - req
      - pandoc-types
      - dhall
      - unordered-containers
      - pandoc
      - tagsoup
      - time
      - mtl
      - containers
      - basic-prelude

executables:
    site:
        source-dirs: app
        main:        site/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - roki-web
        - optparse-applicative
    spa:
        source-dirs: app
        main:        spa/Main.hs
        ghc-options:
        - -threaded
        - -Wall
        - -O2
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - roki-web
        - transformers
        - optparse-applicative
        - hakyll
        - gitrev
        - extra
        - time
        - mtl
        - extra
