services:
  build:
    image: ghcr.io/falgon/roki-web-env:${ROKI_WEB_ENV_IMAGE_TAG:-latest}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    container_name: roki-web-build-ghcr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: apps
    command: /bin/bash -c './site build --preview'
    deploy:
      resources:
        limits:
          memory: 4G
  preview:
    image: ghcr.io/falgon/roki-web-env:${ROKI_WEB_ENV_IMAGE_TAG:-latest}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    container_name: roki-web-preview-ghcr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: apps
    command: /bin/bash -c './site watch --preview --port 8888 --host 0.0.0.0'
    deploy:
      resources:
        limits:
          memory: 4G
  spa:
    image: ghcr.io/falgon/roki-web-env:${ROKI_WEB_ENV_IMAGE_TAG:-latest}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    container_name: roki-web-spa-ghcr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
      - "../.github:/home/rw-c/bin/.github"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: apps
    command: /bin/bash -c './spa yaml -d ${DATE:-""} -b ${BRANCH_NAME:-""} -y'
  clean:
    image: ghcr.io/falgon/roki-web-env:${ROKI_WEB_ENV_IMAGE_TAG:-latest}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    container_name: roki-web-clean-ghcr
    tty: true
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: apps
    command: /bin/bash -c './site clean'
  dev:
    image: ghcr.io/falgon/roki-web-dev:${ROKI_WEB_DEV_IMAGE_TAG:-latest}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    container_name: roki-web-dev-ghcr
    tty: true
    volumes:
      - "../:/home/rw-dev/src"
    ports:
      - "8888:8888"
    working_dir: /home/rw-dev/src
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    deploy:
      resources:
        limits:
          memory: 4G
