name: 'artifacts cleanup'
on:
  schedule:
    - cron: '0 20 * * *' # UTC
  workflow_dispatch:

jobs:
  check-another-workflows:
    runs-on: ubuntu-latest
    outputs:
      is-another-workflows-running: ${{ steps.status_check.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check another workflows status
        id: status_check
        run: |
          acc=0
          for w in "$(find ./${{ env.WORKFLOWS_PATH }} -type f -name '*.yml' -not -name '${{ env.THIS }}'| xargs -n1 basename)"; do
            status="$(gh run list -w $w -L 1 --json status | jq -r '.[].status')"
            val=$(test "$status" = "in_progress" && echo 1 || echo 0)
            acc=$((acc+val))
          done
          echo "status=$acc" >> $GITHUB_OUTPUT
    env:
      WORKFLOWS_PATH: .github/workflows
      THIS: cleanup-artifacts.yml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-artifacts:
    needs: check-another-workflows
    if: ${{ needs.check-another-workflows.outputs.i-another-workflows-running }} = "0"
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 30 minutes
