name: Build Dockerfile and Push GitHub Package Registry
on:
  push:
    branches: [master]
    tags:
      - v*
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    if: github.repository == 'falgon/roki-web'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup environment variables
        run: |
          IMAGE_NAME=$(cat ./docker/.env | grep ROKI_WEB_ENV_IMAGE_NAME | cut -f2 -d=)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" = "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          IMAGE_TAG=$(test $VERSION = master && echo latest || echo $VERSION)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "GH_REGISTRY=docker.pkg.github.com/${{ github.repository }}/$(echo $IMAGE_NAME | cut -f2 -d/):$IMAGE_TAG" >> $GITHUB_ENV
      - name: Login GitHub Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u owner --password-stdin
      - name: Build Image
        run: ROKI_WEB_ENV_IMAGE_TAG=$IMAGE_TAG pushd ./docker && docker-compose build --no-cache --parallel preview; popd
      - name: Push to GitHub Package Registry
        shell: bash
        run: |
          docker tag $IMAGE_NAME $GH_REGISTRY
          docker push $GH_REGISTRY
