name: manually-cleanup-artifacts
on:
  workflow_dispatch:
    inputs:
      limit:
        type: string
        description: age of cleanup artifacts
        required: true
        default: '2 weeks'
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
  steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: ${{ github.event.inputs.limit }}
