name: manually-cleanup-caches
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          readonly BRANCH=${GITHUB_REF#refs/heads/}
          readonly cache_keys=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f1)
          set +e
          for key in $cache_keys; do
              gh actions-cache delete $key -R $REPO -B $BRANCH --confirm
          done
          set -e
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
